rename @skipargcheck -> @unsafe_skipargcheck
simeonschaub/OptionalArgChecks.jl pull request #14
Opened 2020-02-20 11:10 UTC by jw3126

2020-02-20 13:07 UTC, simeonschaub requested changes
Otherwise mostly cosmetic suggestions, but because this is not compatible with `ArgCheck` 1.1 anymore, we should tag a new version and adjust the compat bounds in `Project.toml` accordingly.

2020-02-20 13:07 UTC, simeonschaub commented on src/OptionalArgChecks.jl
> +    _skip(labels, ex, recursive)
I generally try to follow https://github.com/invenia/BlueStyle, which recommends always making the last return statement in multiline function/macro definitions explicit

2020-02-20 13:07 UTC, simeonschaub commented on src/OptionalArgChecks.jl
> +    l = ArgCheck.LABEL_ARGCHECK
Do we want to import `LABEL_ARGCHECK` globally?

2020-02-20 13:07 UTC, simeonschaub commented on src/OptionalArgChecks.jl
> +    _skip([l], ex, true)
See above

2020-02-20 13:07 UTC, simeonschaub commented on src/OptionalArgChecks.jl
> +    @unsafe_skipargcheck ex
It would probably make sense to add `recursive` as an optional argument here too. Maybe even make `false` the default for this? We can always add this later, but we should make a decision, what we want the default to be

2020-02-20 13:07 UTC, simeonschaub commented on src/OptionalArgChecks.jl
> +Elides argument checks created with [`@argcheck`](@ref) or [`@check`](@ref), provided by the package `ArgCheck.jl`.
Could we break up this line to be no longer than 92 characters?

2020-02-20 18:54 UTC, jw3126 commented on src/OptionalArgChecks.jl
> +    @unsafe_skipargcheck ex
I would prefer it if the default is the same for `@skip` and `@unsafe_skipargcheck`, but I am flexible if you wish otherwise.

2020-02-21 08:34 UTC, simeonschaub commented on src/OptionalArgChecks.jl
> +    @unsafe_skipargcheck ex
Ok, makes sense. I'm fine with that

2020-02-21 08:36 UTC, simeonschaub approved these changes
Thanks for the PR! LGTM!

2020-02-21 08:41 UTC, merged